name: lucide_icons
description: A Lucide icon library package for Flutter applications. Fork of Feather Icons, open for anyone to contribute icons.
version: 0.257.0
homepage: https://lucide.dev
repository: https://github.com/lucide-icons/lucide

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  recase: ^4.0.0
  very_good_analysis: ^10.2.0

flutter:
  fonts:
    - family: Lucide
      fonts:
        - asset: assets/lucide.ttf

import_sorter:
  emojis: true
